# Generated by Django 4.2.13 on 2025-01-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expmonth',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expyear',
        ),
    ]
