# Generated by Django 4.2.13 on 2025-01-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
    ]
