# Generated by Django 4.2.13 on 2025-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_order_card_name_remove_order_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='specifications',
            field=models.CharField(default='none', max_length=1000),
            preserve_default=False,
        ),
    ]
